/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import java.util.*;

public class PartOne {
    public static boolean status = false;
    public static int userInput = 0;
// Unlocking code: 837131
// Locking code: 837134

    public static void main(String[] args) {
        Scanner sc = new Scanner(System.in);
        while (true){
            userInput = sc.nextInt();
            userInput = numCheck(userInput);
            if(userInput == 8){
                userInput = sc.nextInt();
                if(userInput == 3){
                    userInput = sc.nextInt();
                    if(userInput == 7){
                        userInput = sc.nextInt();
                        if(userInput == 1){
                            userInput = sc.nextInt();
                            if(userInput == 3){
                                userInput = sc.nextInt();
                                if(userInput == 1){
                                    System.out.println("Unlocked");
                                    status = true;
                                    }    
                                if(userInput == 4){
                                    System.out.println("Locked");
                                    status = false;
                                }    
                            }
                        }
                    }
                }
            }
        } 
    }

    public static int numCheck(int a){
        if (a < 0){
            return 0 - a;
        }
        if (a > 9){
            return 1;
        }
        else{
            return a;
        }
    }
}

