/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import java.util.*;

public class PartTwo {
	
	    public static boolean status = false;
	    public static int userInput = 0;
		
	// Unlocking code: 837131
	// Locking code: 837134
	    public static void main(String[] args) {
			int count = 0;
	        while (status == false){
				Random random = new Random();
	            userInput = numCheck(random.nextInt(10));
	            if(userInput == 8){
	                userInput = numCheck(random.nextInt(10));       
	                if(userInput == 3){
	                    count++;
	                    userInput = numCheck(random.nextInt(10));                    
	                    if(userInput == 7){
	                        count++;
	                        userInput = numCheck(random.nextInt(10));                        
	                        if(userInput == 1){
	                            count++;
	                            userInput = numCheck(random.nextInt(10));
	                            if(userInput == 3){
	                                count++;
	                                userInput = numCheck(random.nextInt(10));
	                                if(userInput == 1){
	                                    count++;
	                                    System.out.println("Unlocked");
	                                    status = true;
	                                    }        
	                            }
	                        }
	                    }
	                }
	            }
				else{
					count++;
				}
	        } 
			System.out.println("Count: " + count);
	    }

		public static int numCheck(int a){
			if (a < 0){
				return 0 - a;
			}
			if (a > 9){
				return 2;
			}
			else{
				return a;
			}
		}
	}
